# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: b06bbb2e6c2bb144c71ac928e1d06c3f7f15ca43c480b1163babee1762a049621d139d2d926332f68cf933c68ce0632646d58cc578905433bfc82454269eb85d

test:
  secret_key_base: b7b78bebc235e396624ca23d10b20395091baa3e99717310db488549ce2797360ffccff9eab2d76afd52fdb712002f687288c723c33cd65c8231b52b07315c9b

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
